//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) {
        System.out.println("ДЗ2-2 типы переменных");
        System.out.println("Задача 1. Объяление перменных");
        int xInt=-2147483648;
        System.out.println("Значение переменной xInt с типом int равно "+xInt);
        byte yByte=-128;
        System.out.println("Значение переменной yByte с типом byte равно "+yByte);
        short zShort=-32768;
        System.out.println("Значение переменной zShort с типом short равно "+zShort);
        long kLong=-9223372036854775808L;
        System.out.println("Значение переменной kLong с типом long равно "+kLong);
        float tFloat=-34.777777f;
        System.out.println("Значение переменной tFloat с типом flaot равно "+tFloat);
        double pDouble=12.1616161616;
        System.out.println("Значение переменной pDouble с типом double равно "+pDouble);
        System.out.println("Задача 2. Инициализация переменных по их типу");
        float a=27.12f;
        System.out.println(+a+" тип перменной float");
        long b=987678965549L;
        System.out.println(+b+" тип перменной long");
        float c=2.786f;
        System.out.println(+c+" тип перменной float");
        short d=569;
        System.out.println(+d+" тип перменной short");
        short e=-159;
        System.out.println(+e+" тип перменной short");
        short f=27897;
        System.out.println(+f+" тип перменной short");
        byte g=67;
        System.out.println(+g+" тип перменной byte");
        System.out.println("Задача 3. Листы бумаги");
        byte lydmilaPavl=23;
        byte annaSerg=27;
        byte ekaterinaAndr=30;
        short paper=480;
        int pupils=lydmilaPavl+annaSerg+ekaterinaAndr;
        int paperPerPupel=paper/pupils;
        System.out.println("На каждого ученика рассчитано "+paperPerPupel+" листов бумаги");
        System.out.println("Задача 4. Производительность машины");
        byte prodA=16/2;
        System.out.println("За минуту машина произвела "+prodA+" штук бутылок");
        int prodB=prodA*20;
        System.out.println("За 20 минут машина произвела "+prodB+" штук бутылок");
        int prodC=prodA*60*24;
        System.out.println("За сутки машина произвела "+prodC+" штук бутылок");
        int prodD=prodC*3;
        System.out.println("За 3 дня машина произвела "+prodD+" штук бутылок");
        int prodE=prodC*30;
        System.out.println("За месяц (30 дней) машина произвела "+prodE+" штук бутылок");
        System.out.println("Задача 5. Краска для ремонта");
        byte canOfPaint=120;
        byte whitePaintClass=2;
        byte brownPaintClass=4;
        int canPerClass=whitePaintClass+brownPaintClass;
        int classSchool=canOfPaint/canPerClass;
        int canWhite=whitePaintClass*classSchool;
        int canBrown=brownPaintClass*classSchool;
        System.out.println("В школе, где "+classSchool+" классов, нужно "+canWhite+" банок белой краски и "+canBrown+" банок коричневой краски");
        System.out.println("Задача 6. Завтрак спортсмена");
        byte banana=5;
        byte bananaWeight=80;
        byte milkVolume100=2;
        byte milk100MlWeight=105;
        byte iceCream=2;
        byte iceCreamWeight=100;
        byte egg=4;
        byte eggWeight=70;
        int smoothieWeight=banana*bananaWeight+milkVolume100*milk100MlWeight+iceCream*iceCreamWeight+egg*eggWeight;
        System.out.println("Вес коктейля "+smoothieWeight+ "г");
        float smoothieWeightKg=smoothieWeight/1000f;
        System.out.println("Вес коктейля "+smoothieWeightKg+ "кг");
        System.out.println("Задача 7. Cпортсмен худеет");
        byte overWeight=7;
        float weightLoss=0.25f;
        float day=overWeight/weightLoss;
        System.out.println("При потере массы тела 250 г за день спортсмен похудеет за "+day+" дней");
        float weightLoss1=0.5f;
        float day1=overWeight/weightLoss1;
        System.out.println("При потере массы тела 500 г за день спортсмен похудеет за "+day1+" дней");
        System.out.println("Задача 8. Повышение ЗП");
        int mashaMonth=67760;
        float mashaMonthNew=mashaMonth*1.1f;
        float mashaYearDiff=mashaMonthNew*12-mashaMonth*12;
        System.out.println("Маша теперь получает "+mashaMonthNew+ "рублей в месяц. Годовой доход вырос на "+mashaYearDiff+" рублей");
        int denisMonth=83690;
        float denisMonthNew=denisMonth*1.1f;
        float denisYearDiff=denisMonthNew*12-denisMonth*12;
        System.out.println("Денис теперь получает "+denisMonthNew+ "рублей в месяц. Годовой доход вырос на "+denisYearDiff+" рублей");
        int kristinaMonth=76230;
        float kristinaMonthNew =kristinaMonth*1.1f;
        float kristinaYearDiff=kristinaMonthNew *12-kristinaMonth*12;
        System.out.println("Кристина теперь получает "+kristinaMonthNew+ "рублей в месяц. Годовой доход вырос на "+kristinaYearDiff+" рублей");
        System.out.println("Конец ДЗ2-2");



    }
}
